#!/bin/sh

### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

test -x $DAEMON || exit 0

DESC="Recommender"
RUNAS=danbooru
PIDFILE=/var/run/recommender/pid
LOGFILE=/var/log/recommender/app.log
APPDIR=/var/lib/recommender/app/web
SCRIPT="/usr/local/bin/gunicorn -D -p $PIDFILE --access-logfile=$LOGFILE --error-logfile=$LOGFILE -b 127.0.0.1:8000 recommender:app --chdir=$APPDIR"

. /lib/init/vars.sh
. /lib/lsb/init-functions

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
  ;;

  stop)
    stop
  ;;

  retart)
    stop
    start
  ;;

  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
  ;;
esac
